### ISSUE TITLE
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: scheme. 

### ISSUE THREAD

**Issue by TENSAE21** [alvinwan/except#4]
Hi there, 
I encounter the above error (full output below) while testing the sample scheme code you provided. I am using python3.5, do you have any ideas as to why?
**********************************************************************

Testing trial.scm on scheme

**********************************************************************
Traceback (most recent call last):
  File "/usr/local/bin/expect", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/uniexpect/main.py", line 45, in main
    for output, data in expect.go():
  File "/usr/local/lib/python3.5/dist-packages/uniexpect/expect.py", line 177, in go
    session = Expect.new_session(settings)
  File "/usr/local/lib/python3.5/dist-packages/uniexpect/expect.py", line 110, in new_session
    continuation_prompt=settings.shell['continuation'])
  File "/usr/local/lib/python3.5/dist-packages/pexpect/replwrap.py", line 38, in __init__
    self.child = pexpect.spawn(cmd_or_spawn, echo=False, encoding='utf-8')
  File "/usr/local/lib/python3.5/dist-packages/pexpect/pty_spawn.py", line 198, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/local/lib/python3.5/dist-packages/pexpect/pty_spawn.py", line 271, in _spawn
    'executable: %s.' % self.command)
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: scheme.

**Comment by alvinwan** [comment]
That means `scheme` is not installed or `scheme` is not symlinked to your scheme installation. You'll have to install scheme before using uniexpect on scheme.
